REMOVE TABLE IF EXISTS vendor;

DEFINE TABLE vendor TYPE NORMAL SCHEMAFULL;

-- warehouses ?

-- details [desc, restock, ]

-- needs type? drop shipping, manufacturer, supplier, re-seller, ... etc (?)

-- order packing
--      bin packing shite?

-- vendor is customer?
--  probably best to start building this from storefront... 
--  why am I so bad at picturing an order flow?

-- reporting tools?
